package com.example2;


import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;


@Entity
@Table(name= "users")   

public class User {

    @Id @GeneratedValue   
    @Column(name = "ID")
    private int ID;
    
    @Column(name = "name")
    private String name;
    
    @Column(name = "email")
    private String email;
    
    @Column(name = "password")
    private String password;


    public User() {
        
    }
    
    public User(String name, String email, String password) {
            //this.ID = id;
            this.name = name;
            this.email = email;
            this.password = password;
    }
    

    public int getID() {return this.ID; }
    public String getName() { return this.name;}
    public String getEmail() { return this.email;}
    public String getPassword() { return this.password;}
    
    //public void setID(int id) { this.ID = id;} // is auto-generated by table
    public void setName(String name) { this.name = name;}
    public void setEmail(String email) { this.email = email;}
    public void setPassword(String password) { this.password = password;}

	}
